Fix/500 error in feature url (#1521)
* Fix crash on some feature URLs

The following kind of URLs: /processes/99999999/f/1, namely, URLs to
features with a non existent participatory process id currently lead to
the following crash:

```
NoMethodError:
  undefined method `features' for nil:NilClass
```

This change fixes that.

* Extract some logic to a method

* Refactor some logic to a separate constraint

* No need to go through the request

* Remove unnecessary check

This constraint should always be nested inside a scope that includes the
:feature_id parameter, but even if that was not the case, and the
parameter was nil, the search for a matching feature would just return
false as expected.

* Fix method documentation

* Compress to one liner

* Final refactor of request constraints

* Remove now unnecessary local variable