[Backport] Fix dynamic controller extensions (undefined method `current_user`) (#5566)
* Fix crashing bug with dynamic controller extensions

When dynamically adding route extensions, Decidim would throw the
following error:

`alias_method': undefined method `current_user' for class
`Decidim::ApplicationController' (NameError)

(cherry picked from commit a700de75b5998ef392f1bf3741a298a6acd77e15)

* Add CHANGELOG entry