Fix possible NoMethodErrors in the notification jobs (#5083)
#### :tophat: What? Why?
We are receiving a lot of the following types of errors from the notification jobs in live instances where we are using Resque to process the jobs:

```
E, [2019-03-15T20:31:58.642308 #32702] ERROR -- : [ActiveJob] [Decidim::NotificationGeneratorJob] [12ab1234-12a3-12a3-ab1c-12ab3c4de567] Error performing Decidim::NotificationGeneratorJob (Job ID: 12ab1234-12a3-12a3-ab1c-12ab3c4de567) from Resque(decidim-production_events) in 1.82ms: NoMethodError (undefined method `constantize' for nil:NilClass):
/path/to/shared/bundle/ruby/2.5.0/gems/decidim-core-0.16.1/app/jobs/decidim/notification_generator_job.rb:9:in `perform'
...
```

```
E, [2019-03-15T20:57:54.092382 #1697] ERROR -- : [ActiveJob] [Decidim::EmailNotificationGeneratorJob] [12ab1234-12a3-12a3-ab1c-12ab3c4de567] Error performing Decidim::EmailNotificationGeneratorJob (Job ID: 12ab1234-12a3-12a3-ab1c-12ab3c4de567) from Resque(decidim-production_events) in 2.62ms: NoMethodError (undefined method `constantize' for nil:NilClass):
/path/to/shared/bundle/ruby/2.5.0/gems/decidim-core-0.16.1/app/jobs/decidim/email_notification_generator_job.rb:9:in `perform'
```

I have no idea what is causing these types of events because the log entries do not contain this information. This fixes at least the jobs that are currently causing a lot of unnecessary load for Resque as it has to write these to the logs. These are logged for each an every instance of the notifications which causes lots of entries e.g. when a notification is triggered for the whole user base (1 log entry * number of users). These log entries are then written very fast by resque to the log as it happens at the same time for the user.

The underlying reason still remains a mystery and would require more investigation.

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [X] Add tests

Co-authored-by: Marc Riera <mrc2407@gmail.com>