Update rails to 6.1 (#8411)
* Bump rails version

* Fixing failing tests in decidim modules

* Fixing Validation syntax
* Use local version of system_test_html_screenshots
* Fixing: "unknown attribute 'service_name' for ActiveStorage::Blob"
* Fix Main spec- Gemfile integrity
* Lint active_storage migrations
* Fix: DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: decidim/application/_documents.html
* Fix: DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: decidim/shared/_follow_button.html
* Fix: DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: decidim/application/_photos.html
* Fix: DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: decidim/shared/_extended_navigation_bar.html
* Fix: DEPRECATION WARNING: Calling  to an ActiveModel::Errors message array in order to add an error is deprecated
* Fix: menu_item_presenter Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
* Fix: permissions_spec.rb:16: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
* Fix: DEPRECATION WARNING: Using `return`, `break` or `throw` to exit a transaction block is deprecated without replacement. If the `throw` came from
* Fix: undefined method `add_template_helper' for ...
* Fix: DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: decidim/application/_attachments.html (called from attachments_for
* Ignore controller specs for now
* Fix: undefined method 'file_fixture_path'
* fix: ArgumentError: wrong number of arguments (given 1, expected 3)
* Fix: Template missing: view:  prefixes
* Fix: ActionMailer queue name
* Running linters
* Fix: wrong number of arguments (given 1, expected 3)
* Fix: DEPRECATION WARNING: create_after_upload! is deprecated and will be removed from Rails 6.2 (use create_and_upload! instead)
* Fix: wrong number of arguments (given 1, expected 3)
* Fix: ERROR:  missing FROM-clause entry for table "component"
* Fix: Cell cache key test
* Fix: undefined method `size' for Rectify::Query
* Fix: DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: decidim/application/_document.html
* Fix: undefined method 'title' for nil:NilClass
* Fix: Template missing: view:  prefixes
* Linters
* Fix: Proposal image test
* Fixing Consultation tests
* Fix Ballout error on elections
* Fix Polling Officer related tests
* Attempt to fix initiative test suite

* Using upgrade branch

* Enable Controller specs

- Fixing Sortitions controller specs
- Fixing Surveys controller specs
- Fixing Accountability controller specs
- Fixing Accountability controller specs
- Fixing Meetings controller specs
- Fixing Proposals controller specs
- Fixing Elections controller specs
- Running Linters
- Fixing failing tests

* Fixing Initiative coverage

* Running linters

* Fix failing test

* Implement review recommendations

* Attempt to increase coverage

* Removing Commented validator

* refactor ScreenshotHelper

* Fixing Admin failing spec

* Linters

* Fixing decidim-generators issues

* Fix Proposal failing spec

* Implement form reommendation changes

* Add changelog notes

* Fix Blog post update_attributes! deprecation warning

* Fix Form Blob

* Revert the route params

* Remove more route params

* Linters and revert of deprecations

* Revert deprecation changes

* Revert more deprecation warnings

* Disable the Fixture file respec helper

* Purge the file_fixture_path references

* Running Linters

* Fixing Decidim-core failing spec

* Remove require statement in capybara

* Revert to Official Decidim repo in generators module